# Generated by Django 4.2.3 on 2023-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='person first name')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=15, verbose_name='last name')),
            ],
            options={
                'db_table': 'its_baby_table',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='person first name')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=15, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1, verbose_name='gender')),
                ('age', models.SmallIntegerField(verbose_name='age')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='weight')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
