# Generated by Django 4.2.3 on 2023-08-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baby',
            options={'verbose_name': 'baby', 'verbose_name_plural': 'babies'},
        ),
    ]
