# Generated by Django 4.2.3 on 2023-08-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_baby_options_alter_baby_first_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baby',
            unique_together={('first_name', 'last_name')},
        ),
    ]
